name: bip39
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/yshrsmz/bip39-dart
author: yshrsmz <the.phantom.bane@gmail.com>

environment:
  sdk: '>=2.0.0-dev.64.1 <3.0.0'

dependencies:
  pointycastle: '^1.0.0-rc2'
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
