name: bip39
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/yshrsmz/bip39-dart
author: yshrsmz <the.phantom.bane@gmail.com>

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  crypto: ^2.0.6
  resource: ^2.1.5
  password_hash: ^2.0.0-beta

#  pointycastle: '^1.0.0-rc2'
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
